def raise_exception_msg(message=""):
    raise ValueError(message)